// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvvboqjvhzsvnqqmzyzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2dmJvcWp2aHpzdm5xcW16eXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODk3NzcsImV4cCI6MjA3MDE2NTc3N30.-ipldi6fFm1fug3g_jHSdB2yHUCRvyRyvY3tZvxfhU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});